### ISSUE TITLE
Will the expanded training dataset in Xwin-math be open sourced?

### ISSUE THREAD

**Issue by slchenchn** [Xwin-LM/Xwin-LM#22]

**Comment by LC-Edward** [comment]
Thanks for your interest to our work! Due to company policies, our training data is currently not publicly available. You can learn about in detail how our synthetic data is constructed through our research paper. [https://arxiv.org/pdf/2403.04706.pdf](https://arxiv.org/pdf/2403.04706.pdf)

**Comment by iFe1er** [comment]
> Thanks for your interest in our work! Due to company policies, our training data is currently not publicly available. You can learn about in detail how our synthetic data is constructed through our research paper. https://arxiv.org/pdf/2403.04706.pdf

I wonder why the model result reported in https://arxiv.org/pdf/2403.04706.pdf is not the same as the result reported in github project? I@LC-Edward
