### ISSUE TITLE
It is hoped that INT8/INT4 quantization guidelines will be given and GPTQ will be supported

### ISSUE THREAD

**Issue by one0oneChen** [Xwin-LM/Xwin-LM#6]
Congratulations, this is a victory for open source, a brand new milestone! Thank you for your great work! It is hoped that INT8/INT4 quantization guidelines will be given and GPTQ will be supported

**Comment by REIGN12** [comment]
Hi @one0oneChen ! Many thanks for your attention! 
We have noticed that GPTQ version of models are already supported by TheBloke!
Here are the links to **GPTQ** models converted by TheBloke:
* Xwin-LM-7b-V0.1: https://huggingface.co/TheBloke/Xwin-LM-7B-V0.1-GPTQ
* Xwin-LM-13b-V0.1: https://huggingface.co/TheBloke/Xwin-LM-13B-V0.1-GPTQ
* Xwin-LM-70b-V0.1: https://huggingface.co/TheBloke/Xwin-LM-70B-V0.1-GPTQ
