### ISSUE TITLE
This modle can be infered/finetuned by  Fastchat ?

### ISSUE THREAD

**Issue by wanzhu666666** [Xwin-LM/Xwin-LM#9]

**Comment by REIGN12** [comment]
Hi @wanzhu666666! 
Since Xwin-LM-V0.1 series of models are finetuned from Llama2 pretrained models, we believe they can be directly infered/finetuned by Fastchat repo.

**Comment by REIGN12** [comment]
> Hi @wanzhu666666! Since Xwin-LM-V0.1 series of models are finetuned from Llama2 pretrained models, we believe they can be directly infered/finetuned by Fastchat repo.

One kind reminder is that you need to use exactly the same conversation template mentioned here in the README.md, which is actually the same as Vicuna~
